name: Check

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-arm, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v6if

    - name: Create target directory
      if: matrix.os == 'windows-latest'
      run: |
        mkdir C:\Programming\Java

    - name: Copy repository
      if: matrix.os == 'windows-latest'
      run: |
        xcopy "${{ github.workspace }}" "C:\Programming\Java" /E /I /Y

    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5
      with:
        gradle-version: '7.1.1'

    - name: Run checks with Gradle (Linux, macOS)
      if: matrix.os != 'windows-latest'
      # Use gradle from "Setup Gradle" for faster CI builds
      run: gradle check
    - name: Run checks with Gradle (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        cd C:\Programming\Java
        gradle check
